version: '3.8'

services:
  postgres:
    image: postgres
    container_name: ntd_database_container
    environment:
      POSTGRES_DB: ntd_database
      POSTGRES_USER: database_user
      POSTGRES_PASSWORD: database_password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: