# Generated by Django 5.2.1 on 2025-06-11 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Climate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Terrain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='planet',
            name='climates',
        ),
        migrations.RemoveField(
            model_name='planet',
            name='terrains',
        ),
        migrations.AddField(
            model_name='planet',
            name='climates',
            field=models.ManyToManyField(blank=True, to='api.climate'),
        ),
        migrations.AddField(
            model_name='planet',
            name='terrains',
            field=models.ManyToManyField(blank=True, to='api.terrain'),
        ),
    ]
