# Generated by Django 5.2.1 on 2025-06-11 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_climate_terrain_remove_planet_climates_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='climate',
            name='id',
        ),
        migrations.RemoveField(
            model_name='terrain',
            name='id',
        ),
        migrations.AlterField(
            model_name='climate',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='terrain',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
